# Nom du workflow
name: Deploy to Heroku

# Déclenchement du workflow sur chaque push vers la branche principale
on:
  push:
    branches: [main]

# Définition des jobs du workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Construction, push et déploiement du conteneur Docker vers Heroku
      - name: Build, push, and release Docker container to Heroku
        uses: gonuit/heroku_docker_deploy@v1.3.3
        with:
          # Adresse e-mail associée au compte Heroku
          email: ${{ secrets.HEROKU_EMAIL }}

          # Clé API Heroku associée à l'utilisateur
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Nom de l'application Heroku
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # (Optionnel, par défaut : "./")
          # Répertoire contenant le Dockerfile
          dockerfile_directory: ./

          # (Optionnel, par défaut : "Dockerfile")
          # Nom du Dockerfile
          dockerfile_name: Dockerfile
