# Nom du workflow
name: Deploy to Heroku

# Déclenchement du workflow sur chaque push vers la branche principale
on:
  push:
    branches: [main]

# Définition des jobs du workflow
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Connexion au registre de conteneurs Heroku
      - name: Log in to Heroku Container Registry
        run: echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username="${{ secrets.HEROKU_EMAIL }}" --password-stdin registry.heroku.com

      # Étape 3 : Construire l'image Docker
      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      # Étape 4 : Pousser l'image Docker vers Heroku
      - name: Push Docker image to Heroku
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Étape 5 : Publier le conteneur Docker sur Heroku
      - name: Release Docker image on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
